# -*- coding: utf-8 -*-
"""Faghihzade

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m9Ef-A8Syz4EmawFmlr0kninMroujJLW
"""

import numpy as np
x = np.arange(0,2*np.pi,(2*np.pi/100))
y= np.sin(x)
x

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=2)
len(x_train)

import tensorflow as tf
ANN = tf.keras.models.Sequential()
ANN.add(tf.keras.layers.Dense(units=50,activation='sigmoid'))
ANN.add(tf.keras.layers.Dense(units=100,activation='sigmoid'))

ANN.add(tf.keras.layers.Dense(units=1,activation='linear'))

ANN.compile(optimizer = 'adam' , loss = 'mean_squared_error' , metrics = ['mean_squared_error'])

ANN.fit(x_train,y_train,batch_size=32,epochs=1000)